executable = VetoAnalysis.sh
arguments = $(ClusterId) $(ProcId) $(RUNN)
output = output/VetoAnalysis.$(ClusterId).$(ProcId).out
error = error/VetoAnalysis.$(ClusterId).$(ProcId).err
log = log/VetoAnalysis.$(ClusterId).log
+JobFlavour = "workday"
notification = Never
on_exit_remove          = (ExitBySignal == False) && ((ExitCode == 1) || (ExitCode == 0))
max_retries             = 3
queue RUNN in 100789, 100791, 100792, 100793, 100794, 100796, 100797